### ISSUE TITLE
Tab/tab-completion causes prompt rewrite to remove one line

### ISSUE THREAD

**Issue by thor** [eproxus/pad.zsh-theme#1] opened 2015-03-23 12:13 UTC
I came across the project and thought I'd claim the honor of issue #1.

Whenever I "enter" into tab-completion, as the suggestions for the tab-completion are presented, the prompt is rewritten one line upwards. This is somewhat... disturbing. 
I'm on zsh 5.0.7, with the latest (as of today) oh-my-zsh release, with only git and svn enabled. (I edited the two branch checks to check if their respective plugin was enabled before trying to get the status.)

I don't have too much experience with the prompt configuration, so I'm hoping you've got a better idea than me here. :+1:

**Comment by eproxus** [comment] 2015-08-26 16:02
Wow, sorry for leaving you hanging for so long! (Completely missed this issue)

I've seen this as well, but that was long ago. Now I can't reproduce it. I'm on zsh 5.0.8 (x86_64-apple-darwin14.3.0).

**Comment by thor** [comment] 2015-08-31 06:55
I guess time flies! :)
I'll see if I can reproduce it -- nowadays I've left oh-my-zsh for zproto, which is a bit more modular and not as full of everything.

**Comment by eproxus** [comment] 2015-08-31 07:16
Yeah, I'm using [antigen](https://github.com/zsh-users/antigen) now with the Git plugin from oh-my-zsh, which feels much more lightweight. I'm trying to replace the oh-my-zsh Git functions with [`git-radar`](https://github.com/michaeldfallen/git-radar) but it doesn't work exactly like I want it to yet...

**Comment by eproxus** [comment] 2017-04-18 12:11
Since I've switched to gitHUD, I'm closing this for now. Please re-open if you need additional support.

**Closed as completed by eproxus** 2017-04-18 12:11 UTC
